// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactNative = require("react-native");

var width = ReactNative.Dimensions.get("window").width;

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: "#F5FCFF",
        alignItems: "flex-start",
        flex: 1,
        justifyContent: "center"
      },
      label: {
        fontSize: 20,
        textAlign: "center",
        alignItems: "center",
        margin: 10
      },
      input: {
        borderColor: "gray",
        borderWidth: 1,
        height: 45,
        width: width
      },
      fancyButton: {
        backgroundColor: "lightblue",
        borderBottomRightRadius: 4,
        borderColor: "gray",
        borderWidth: 1,
        marginTop: 10,
        width: width
      }
    });

function App12(Props) {
  var match = React.useState(function () {
        return false;
      });
  var match$1 = React.useState(function () {
        return "";
      });
  var setUser = match$1[1];
  var match$2 = React.useState(function () {
        return "";
      });
  var setPassword = match$2[1];
  var match$3 = React.useState(function () {
        return "";
      });
  var setEmail = match$3[1];
  return React.createElement(ReactNative.View, {
              style: styles.container,
              children: null
            }, React.createElement(ReactNative.Text, {
                  style: styles.label,
                  children: "username"
                }), React.createElement(ReactNative.TextInput, {
                  onChangeText: (function (user) {
                      return Curry._1(setUser, (function (param) {
                                    return user;
                                  }));
                    }),
                  value: match$1[0],
                  style: styles.input
                }), React.createElement(ReactNative.Text, {
                  style: styles.label,
                  children: "password"
                }), React.createElement(ReactNative.TextInput, {
                  onChangeText: (function (password) {
                      return Curry._1(setPassword, (function (param) {
                                    return password;
                                  }));
                    }),
                  value: match$2[0],
                  style: styles.input
                }), match[0] ? React.createElement(ReactNative.TouchableOpacity, {
                    style: styles.fancyButton,
                    children: React.createElement(ReactNative.Text, {
                          style: styles.label,
                          children: "Log in"
                        })
                  }) : React.createElement(React.Fragment, {
                    children: null
                  }, React.createElement(ReactNative.Text, {
                        style: styles.label,
                        children: "email"
                      }), React.createElement(ReactNative.TextInput, {
                        onChangeText: (function (email) {
                            return Curry._1(setEmail, (function (param) {
                                          return email;
                                        }));
                          }),
                        value: match$3[0],
                        style: styles.input
                      }), React.createElement(ReactNative.TouchableOpacity, {
                        style: styles.fancyButton,
                        children: React.createElement(ReactNative.Text, {
                              style: styles.label,
                              children: "Sign up"
                            })
                      })));
}

var make = App12;

exports.styles = styles;
exports.make = make;
/* width Not a pure module */
