// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Colors = require("./Colors.bs.js");
var Buttons = require("./Buttons.bs.js");
var Metrics = require("./Metrics.bs.js");
var ReactNative = require("react-native");

var styles = ReactNative.StyleSheet.create({
      container: {
        backgroundColor: Colors.colors.background,
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      label: {
        fontSize: 20,
        textAlign: "center",
        alignItems: "center",
        margin: 10
      },
      input: {
        borderColor: Colors.colors.commonBorderColor,
        borderWidth: 1,
        height: 45,
        width: Metrics.metrics.screenWidth
      },
      fancyButton: [
        Buttons.commonButton,
        {
          backgroundColor: Colors.colors.buttonColor,
          borderColor: Colors.colors.commonBorderColor
        }
      ],
      loginButton: [
        Buttons.commonButton,
        {
          backgroundColor: "grey",
          borderColor: "lightblue"
        }
      ]
    });

exports.styles = styles;
/* styles Not a pure module */
