// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

var width = ReactNative.Dimensions.get("window").width;

var commonButton = {
  borderBottomLeftRadius: 4,
  borderBottomRightRadius: 4,
  borderWidth: 1,
  marginTop: 10,
  width: width
};

exports.commonButton = commonButton;
/* width Not a pure module */
