// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var colors = {
  background: "#F5FCFF",
  commonBorderColor: "gray",
  buttonColor: "lightblue"
};

exports.colors = colors;
/* No side effect */
