// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

var width = ReactNative.Dimensions.get("window").width;

var height = ReactNative.Dimensions.get("window").height;

var metrics_screenWidth = width < height ? width : height;

var metrics_screenHeight = width < height ? height : width;

var metrics = {
  screenWidth: metrics_screenWidth,
  screenHeight: metrics_screenHeight
};

exports.metrics = metrics;
/* width Not a pure module */
