// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var ReactNative = require("react-native");

var styles = ReactNative.StyleSheet.create({
      app: {
        marginHorizontal: "auto",
        maxWidth: 500
      },
      logo: {
        height: 80
      },
      header: {
        padding: 20
      },
      text: {
        fontSize: 18,
        lineHeight: 24,
        textAlign: "center",
        marginVertical: 16
      },
      title: {
        fontSize: 24,
        fontWeight: "bold",
        textAlign: "center",
        marginVertical: 16
      },
      link: {
        color: "#1B95E0"
      },
      code: {
        fontFamily: "monospace"
      },
      container: {
        backgroundColor: "#F5FCFF",
        alignItems: "center",
        flex: 1,
        justifyContent: "center"
      },
      welcome: {
        fontSize: 20,
        textAlign: "center",
        margin: 10
      },
      instructions: {
        color: "#333333",
        textAlign: "center",
        marginBottom: 5
      }
    });

exports.styles = styles;
/* styles Not a pure module */
