// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var style = {
  normal: /* FontSize */{
    _0: 16
  }
};

var size = {
  regular: 16
};

exports.size = size;
exports.style = style;
/* No side effect */
