// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var TextLink = require("./TextLink").default;
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var make = TextLink;

var Wrapper = {
  make: make
};

function ViewLink(Props) {
  var href = Props.href;
  var accessibilityLabel = Props.accessibilityLabel;
  var s = Props.style;
  var activeStyle = Props.activeStyle;
  var children = Props.children;
  var tmp = {
    href: href,
    style: [
      {
        display: "flex",
        flexDirection: "column"
      },
      s
    ],
    children: children
  };
  if (accessibilityLabel !== undefined) {
    tmp.accessibilityLabel = Caml_option.valFromOption(accessibilityLabel);
  }
  if (activeStyle !== undefined) {
    tmp.activeStyle = Caml_option.valFromOption(activeStyle);
  }
  return React.createElement(make, tmp);
}

var make$1 = ViewLink;

exports.Wrapper = Wrapper;
exports.make = make$1;
/* make Not a pure module */
