// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Link = require("./Link.bs.js");
var Utils = require("./Utils.bs.js");
var React = require("react");
var Styles = require("./styles/Styles.bs.js");
var ReactNative = require("react-native");

function App(Props) {
  return React.createElement(ReactNative.View, {
              style: Styles.styles.app,
              children: null
            }, React.createElement(ReactNative.View, {
                  style: Styles.styles.header,
                  children: null
                }, React.createElement(ReactNative.Image, {
                      accessibilityLabel: "React logo",
                      resizeMode: "contain",
                      source: require("./assets/logoUri.svg"),
                      style: Styles.styles.logo
                    }), React.createElement(ReactNative.Text, {
                      style: Styles.styles.title,
                      children: Utils.s("React Native for Web")
                    })), React.createElement(ReactNative.Text, {
                  style: Styles.styles.text,
                  children: null
                }, Utils.s("This is an example of an app built with "), React.createElement(Link.make, {
                      href: "https://github.com/facebook/create-react-app",
                      value: "Create React App"
                    }), Utils.s(" and "), React.createElement(Link.make, {
                      href: "https://github.com/necolas/react-native-web",
                      value: "React Native for Web"
                    })), React.createElement(ReactNative.Text, {
                  style: Styles.styles.text,
                  children: null
                }, Utils.s("To get started, edit "), React.createElement(Link.make, {
                      href: "https://codesandbox.io/s/q4qymyp2l6/",
                      style: Styles.styles.code,
                      value: "src/App.js"
                    }), Utils.s(". ")), React.createElement(ReactNative.Button, {
                  onPress: (function (_e) {
                      console.log("Example button pressed");
                      
                    }),
                  title: "Example button"
                }));
}

var make = App;

exports.make = make;
/* Link Not a pure module */
