// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Styles = require("./styles/Styles.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReactNative = require("react-native");

function Link(Props) {
  var href = Props.href;
  var style = Props.style;
  var value = Props.value;
  var linkStyle = style !== undefined ? [
      Styles.styles.link,
      Caml_option.valFromOption(style)
    ] : Styles.styles.link;
  return React.createElement(ReactNative.Text, {
              onPress: (function (_e) {
                  ReactNative.Linking.openURL(href).then(function (param) {
                        return Promise.resolve((console.log("opened " + href), undefined));
                      });
                  
                }),
              style: linkStyle,
              value: value
            });
}

var make = Link;

exports.make = make;
/* react Not a pure module */
